export const WHATSAPP_NUMBER = '528444281015';

export const dressingSides = ['Sin aderezo', 'Chipotle', 'Salsa italiana', 'Barbecue'];
export const saladDressings = ['Blue Cheese', 'Chipotle', 'Barbecue', 'Vinagreta miel-limón'];
export const syrups = [
  'Vainilla francesa',
  'Caramelo salado',
  'Vainilla francesa sin azúcar',
  'Caramelo salado sin azúcar',
];
export const milkTypes = ['Entera', 'Deslactosada'];
export const crepeFlavors = ['Nutella', 'Cajeta', 'Queso crema dulce', 'Lechera', 'Fresa', 'Plátano', 'Nuez'];
export const savoryCrepeFlavors = ['Jamón de pavo', 'Pepperoni', 'Queso manchego', 'Queso mozzarella', 'Mix quesos'];

export const categories = [
  { id: 'paninis', label: 'Paninis', emoji: '🥪' },
  { id: 'wraps', label: 'Wraps', emoji: '🌯' },
  { id: 'ensaladas', label: 'Ensaladas', emoji: '🥗' },
  { id: 'crepas', label: 'Crepas', emoji: '🥞' },
  { id: 'cafe', label: 'Café', emoji: '☕' },
  { id: 'bebidas', label: 'Bebidas', emoji: '🥤' },
];

export const products = [
  {
    id: 'panini-pollo-chipotle',
    category: 'paninis',
    type: 'panini',
    name: 'Panini Pollo Chipotle',
    price: 100,
    badge: 'Nuevo',
    description: 'Pechuga de pollo, queso manchego y aderezo chipotle en pan chapata.',
    ingredients: 'Pechuga de pollo, queso manchego, aderezo chipotle, pan chapata.',
    image: '',
  },
  {
    id: 'panini-pollo-bbq',
    category: 'paninis',
    type: 'panini',
    name: 'Panini Pollo BBQ',
    price: 100,
    description: 'Pechuga de pollo, queso manchego y salsa barbecue en pan chapata.',
    ingredients: 'Pechuga de pollo, queso manchego, salsa barbecue, pan chapata.',
    image: '',
  },
  {
    id: 'panini-pizza',
    category: 'paninis',
    type: 'panini',
    name: 'Panini Pizza',
    price: 80,
    description: 'Pepperoni, queso manchego y salsa de tomate en pan chapata.',
    ingredients: 'Pepperoni, queso manchego, salsa de tomate, pan chapata.',
    image: '',
  },
  {
    id: 'panini-jamon-queso',
    category: 'paninis',
    type: 'panini',
    name: 'Panini Jamón & Queso',
    price: 80,
    description: 'Jamón de pavo, queso manchego y mayonesa en pan chapata.',
    ingredients: 'Jamón de pavo, queso manchego, mayonesa, pan chapata.',
    image: '',
  },
  {
    id: 'wrap-pollo-chipotle',
    category: 'wraps',
    type: 'wrap',
    name: 'Wrap Pollo Chipotle',
    price: 100,
    badge: 'Fresco',
    description: 'Pollo, lechuga, jitomate, queso manchego y chipotle.',
    ingredients: 'Pollo, lechuga, jitomate, queso manchego, chipotle, tortilla wrap.',
    defaultSideDressing: 'Chipotle',
    image: '',
  },
  {
    id: 'wrap-pollo-bbq',
    category: 'wraps',
    type: 'wrap',
    name: 'Wrap Pollo BBQ',
    price: 100,
    description: 'Pollo BBQ, lechuga, queso manchego y cebolla morada.',
    ingredients: 'Pollo BBQ, lechuga, queso manchego, cebolla morada, tortilla wrap.',
    defaultSideDressing: 'Barbecue',
    image: '',
  },
  {
    id: 'wrap-jamon-queso',
    category: 'wraps',
    type: 'wrap',
    name: 'Wrap Jamón & Queso',
    price: 90,
    description: 'Jamón, lechuga, jitomate, queso manchego y mayonesa.',
    ingredients: 'Jamón de pavo, lechuga, jitomate, queso manchego, mayonesa, tortilla wrap.',
    defaultSideDressing: 'Chipotle',
    image: '',
  },
  {
    id: 'ensalada-blue',
    category: 'ensaladas',
    type: 'salad',
    name: 'Ensalada Blue Cheese',
    price: 110,
    description: 'Lechuga, pollo a la plancha, queso manchego y crutones.',
    ingredients: 'Lechuga, pollo a la plancha, queso manchego, crutones.',
    defaultDressing: 'Blue Cheese',
    image: '',
  },
  {
    id: 'ensalada-chipotle',
    category: 'ensaladas',
    type: 'salad',
    name: 'Ensalada Chipotle',
    price: 110,
    description: 'Lechuga, pollo a la plancha, queso manchego y tortilla crujiente.',
    ingredients: 'Lechuga, pollo a la plancha, queso manchego, tortilla crujiente.',
    defaultDressing: 'Chipotle',
    image: '',
  },
  {
    id: 'ensalada-bbq',
    category: 'ensaladas',
    type: 'salad',
    name: 'Ensalada BBQ',
    price: 110,
    description: 'Lechuga, pollo BBQ, queso manchego y cebolla morada.',
    ingredients: 'Lechuga, pollo BBQ, queso manchego, cebolla morada.',
    defaultDressing: 'Barbecue',
    image: '',
  },
  {
    id: 'ensalada-fresa-nuez',
    category: 'ensaladas',
    type: 'salad',
    name: 'Ensalada Fresa & Nuez',
    price: 110,
    badge: 'Especialidad',
    description: 'Lechuga, pollo a la plancha, fresa, nuez y queso manchego.',
    ingredients: 'Lechuga, pollo a la plancha, fresa, nuez, queso manchego.',
    defaultDressing: 'Vinagreta miel-limón',
    image: '',
  },
  {
    id: 'crepa-dulce',
    category: 'crepas',
    type: 'crepe',
    name: 'Crepa Dulce',
    price: 70,
    badge: '2 sabores incluidos',
    description: 'Elige de 1 a 2 sabores incluidos. Agrega toppings extra por $10 c/u.',
    ingredients: 'Crepa dulce con los sabores que elijas.',
    image: '',
  },
  {
    id: 'crepa-salada',
    category: 'crepas',
    type: 'crepe',
    name: 'Crepa Salada',
    price: 70,
    badge: '2 ingredientes incluidos',
    description: 'Elige de 1 a 2 ingredientes incluidos. Agrega extras por $10 c/u.',
    ingredients: 'Crepa salada con los ingredientes que elijas.',
    image: '',
  },
  {
    id: 'americano',
    category: 'cafe',
    type: 'coffee',
    name: 'Americano',
    price: 45,
    description: 'Caliente o helado. Jarabe opcional por $10.',
    ingredients: 'Café americano. Jarabe opcional.',
    image: '',
  },
  {
    id: 'latte',
    category: 'cafe',
    type: 'coffee',
    name: 'Latte',
    price: 55,
    description: 'Caliente o helado. Elige leche entera o deslactosada. Jarabe opcional por $10.',
    ingredients: 'Espresso, leche entera o deslactosada. Jarabe opcional.',
    image: '',
  },
  {
    id: 'frappe',
    category: 'cafe',
    type: 'coffee',
    name: 'Frappé',
    price: 70,
    description: 'Frappe helado. Elige leche entera o deslactosada. Agrega crema batida por $10.',
    ingredients: 'Café, hielo, leche entera o deslactosada. Crema batida opcional.',
    image: '',
  },
  {
    id: 'coca',
    category: 'bebidas',
    type: 'simple',
    name: 'Coca-Cola',
    price: 30,
    description: 'Refresco frío.',
    ingredients: 'Coca-Cola.',
    image: '',
  },
  {
    id: 'coca-light',
    category: 'bebidas',
    type: 'simple',
    name: 'Coca-Cola Light',
    price: 30,
    description: 'Refresco frío.',
    ingredients: 'Coca-Cola Light.',
    image: '',
  },
  {
    id: 'agua',
    category: 'bebidas',
    type: 'simple',
    name: 'Agua',
    price: 25,
    description: 'Botella de agua.',
    ingredients: 'Agua embotellada.',
    image: '',
  },
];
